### ISSUE TITLE
Stderr is not logged

### ISSUE THREAD

**Issue by Ondraceq** [paradise-fi/surveyor#6]
It is probably captured, but then thrown away in `podman.py`.
I suggest adding `stderr` next to `output` in the resulting json.

**Comment by Ondraceq** [comment]
My investigation:
`stderr` that is returned in `invokePodmanCommand` is never used (when the return value is used, it's used as `invokePodmanCommand(...)[0]`)

**Comment by Ondraceq** [comment]
Worked before ... https://github.com/containers/podman/pull/8686

**Comment by yaqwsx** [comment]
Fixed in https://github.com/paradise-fi/surveyor/commit/8d22b28f9b677b2d6251a15734e214200cfe10e7
